sonar.projectKey=VitorHsC9_capitais
sonar.organization=vitorhsc9
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
